# Generated by Django 3.2.7 on 2021-10-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_guest_honorific'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default='', max_length=100)),
                ('last', models.CharField(default='', max_length=100)),
                ('position', models.CharField(choices=[('CON', 'Concierge'), ('BH', 'Bellhop'), ('KIT', 'Kitchen'), ('CUS', 'Custodial')], default='CON', max_length=3)),
                ('ssn', models.CharField(default='', max_length=12)),
                ('hourly_rate', models.FloatField(default=12.5)),
                ('hire_date', models.DateField()),
            ],
        ),
    ]
